language: node_js

node_js:
  - '0.10'

addons:
  sauce_connect: true

install:
  - npm install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
  - npm start
  - sleep 2

script:
  - npm test

